<style>
    #main-nav {
        margin-bottom:20px;
    }
.area-container > h2{
    font-size:18px;font-weight:700;
}
.area-blocks {
    margin-top:15px;
    margin-left:-15px;
}
.area-block-col .image-btn{
    margin-left:15px;
}
.area-block-col {
    position:relative;
}
.image-btn {
    display:block;
    position: relative;
    background-size: 100% 100%;
    background-repeat: no-repeat;
}
.image-btn-h1 {
    height:285px;
}
.image-btn-h2 {
    height:288px;
}
.image-btn > span {
    display:block;
    position:absolute;
    left:0;right:0;bottom:0;
    padding:10px;
    background:rgba(0, 0, 0, .3);
    font-size:20px;
    font-weight:bold;
    color:#fff;
}
.image-btn > span > i {
    color: #fff;
    margin-left: 10px;
    font-size: 16px;
    font-style: normal;
    font-weight:200;
}
#livechat-compact-container {
    display:none;
}
</style>
<div class="container area-container">
    <h2><?php _tt('Choose location', '请选择区域')?></h2>
    <div class="area-blocks lay-g">
        <div class="area-block-col lay-u-1-2">
            <a href="//ma<?php echo domain()?>" class="image-btn image-btn-h1" style="background-image:url(<?php echo media_url('area/ma.jpg')?>)">
                <span>
                    <?php _tt('Boston', '波士顿')?>
                    <i>(<?php _tt('Massachusetts', '马萨诸塞州')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-2">
            <a href="//ny<?php echo domain()?>" class="image-btn image-btn-h1" style="background-image:url(<?php echo media_url('area/ny.jpg')?>)">
                <span>
                    <?php _tt('New York', '纽约')?>
                    <!--<i>(<?php _tt('New York', '纽约')?>)</i>-->
                </span>
            </a>
        </div>
    </div>
    <div class="area-blocks lay-g" style="margin-top:15px">
        <div class="area-block-col lay-u-1-3">
            <a href="//ga<?php echo domain()?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/ga.jpg')?>)">
                <span>
                    <?php _tt('Atlanta', '亚特兰大')?>
                    <i>(<?php _tt('Georgia', '佐治亚州')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-3">
            <a href="//ca<?php echo domain()?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/ca.jpg')?>)">
                <span>
                    <?php _tt('Los Angel', '洛杉矶')?>
                    <i>(<?php _tt('California', '加利福尼亚')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-3">
            <a href="//il<?php echo domain()?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/il.jpg')?>)">
                <span>
                    <?php _tt('Chicago', '芝加哥')?>
                    <i>(<?php _tt('Illinois', '伊利诺斯')?>)</i>
                </span>
            </a>
        </div>
    </div>
</div>