<style>
.area-container > h2{
    font-size:18px;font-weight:700;
}
.area-blocks {
    margin-top:15px;
    margin-left:-15px;
}
.area-block-col .image-btn{
    margin-left:15px;
}
.area-block-col {
    position:relative;
}
.image-btn {
    display:block;
    position: relative;
    background-size: 100% 100%;
    background-repeat: no-repeat;
}
.image-btn-a {
    height:590px;
}
.image-btn-b, .image-btn-c {
    height:287px;
}
.image-btn-c {
    margin-top:15px;
}
.image-btn > span {
    display:block;
    position:absolute;
    left:0;right:0;bottom:0;
    padding:10px;
    background:rgba(0, 0, 0, .3);
    font-size:20px;
    font-weight:bold;
    color:#fff;
}
.image-btn > span > i {
    color: #fff;
    margin-left: 10px;
    font-size: 16px;
    font-style: normal;
    font-weight:200;
}
</style>
<div class="container area-container">
    <h2><?php _tt('Choose location', '请选择区域')?></h2>
    <div class="area-blocks lay-g">
        <div class="area-block-col lay-u-1-2">
            <a href="http://ma<?php echo domain()?>" class="image-btn image-btn-a" style="background-image:url(<?php echo media_url('area/ma.jpg')?>)">
                <span>
                    <?php _tt('Boston', '波士顿')?>
                    <i>(<?php _tt('Massachusetts', '马萨诸塞州')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-2">
            <a href="javascript:void(0)" class="image-btn image-btn-b" style="background-image:url(<?php echo media_url('area/b.jpg')?>)">
                <span>
                    <?php _tt('New York', '纽约')?>
                    <i>(<?php _tt('NYC, Long island, Brooklyn', '纽约市，长岛，布鲁克林')?>)</i>
                </span>
            </a>
            <a href="javascript:void(0)" class="image-btn image-btn-c" style="background-image:url(<?php echo media_url('area/c.jpg')?>)">
                <span><?php _tt('Washington', '华盛顿')?>
                    <i>(<?php _tt('DC, MD, VA', '华盛顿DC，弗吉尼亚，马里兰')?>)</i>
                </span>
            </a>
        </div>
    </div>
</div>