<?php
    use \module\home\widgets as HomeWidgets;
    use \module\page\widgets as PageWidgets;
    use \module\schooldistrict\widgets\home as SchooldistrictWidgets;
    use \module\estate\widgets\home as EstateWidgets;
    use \module\yellowpage\widgets\home as YellowPageWidgets;
    use \module\customer\widgets\home as CustomerWidgets;

    $this->title = tt('Usleju', '米乐居');
    $this->keywords = '';

    $this->params['activeNavId'] = 'home';
?>

<div id="header">
    <?php echo PageWidgets\Nav::widget()?>
    <div class="container rets-start-box">
        <?php echo HomeWidgets\TopBanner::widget()?>
    </div>
</div>


<div class="top-description">
    <img src="<?php echo media_url('egimgs/ma.jpg')?>" alt="<?php echo \WS::$app->area->name[1]?>买房 - 美国买房 - 米乐居">
    米乐居 - <?php echo \WS::$app->area->name[1]?> 是美国房地产网络平台，本站为用户提供最新、最全的实时房源，提供国内用户一条龙房产服务。让您不再为海外置业选房、看房、买房、养房发愁。
</div>
<?php if(! \WS::$app->isSeoCrawlerAccess()):?>
<style>.top-description{display:none;}</style>
<?php endif?>

<div class="container">
    <?php echo HomeWidgets\MarketingGuarantee::widget()?>
</div>

<div style="background:#f8f8f8">
    <?php if (\WS::$app->area->id === 'ma'):?>
      <div class="container mt40">
          <?php echo SchooldistrictWidgets\Top::widget()?>
      </div>
    <?php endif?>

    <?php echo HomeWidgets\Market::widget()?>

    <div class="container mt50">
        <?php echo EstateWidgets\Top::widget()?>
    </div>

    <div class="container mt50">
        <?php echo YellowPageWidgets\Top::widget()?>
    </div>

    <div class="container mt50">
        <?php echo CustomerWidgets\Story::widget()?>
    </div>
</div>