<?php
    $_options = ['position'=>$this::POS_HEAD, 'depends' => '\module\page\assets\Asset'];

    $this->registerJsFile('/static/js/jquery.raty.js', $_options);
    $this->registerJsFile('/static/js/comment.js', $_options);

    $_context = $this->context;
    $t = lang('comment');
?>
<div class="reviews-box" id="comment-body">
    <div class="action-box">
        <div class="bar">
            <div class="text">
                (<?php $t('Reviews')?><span class="displayCount">
                    <em>0</em>
                </span>
                )
            </div>
            <button class="btn btn-lg" id="btn-begin-comment" data-toggle="modal" data-target="#comment-form-window"><?php $t('Write Comments')?></button>
        </div>
    </div>
    <div class="list" id="comment-items">
        <!--review list content-->        
    </div>
    <div class="userPanel">
        <!-- 评论 -->
        <div class="modal fade" id="comment-form-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">
                                &times;
                            </span>
                            <span class="sr-only">
                                <?php $t('Close')?>
                            </span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            <?php $t('Write Comments')?>
                        </h4>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="#" class="loginForm autoSubmitForm" id="comment-form">
                            <input name="_csrf" type="hidden" id="_csrf" value="<?= Yii::$app->request->csrfToken ?>">
                            <div class="userInfo clearfix">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <?php _tt('Rating', '评分')?>
                                    </span>
                                    <div class="form-control" id="comment-rating" style="float:none;cursor: pointer;"></div>
                                    <script type="text/javascript">
                                    $(function(){
                                        $('#comment-rating').raty({
                                            hintList: [
                                                'Bad', 
                                                'Poor?>', 
                                                'Regular', 
                                                'Good', 
                                                'Gorgeous'],
                                            start: 1,
                                            scoreName: 'rating',
                                            showCancel: false,
                                            path: '/static/img/',
                                            onClick: function(score) {}
                                        });
                                    });
                                    </script>
                                </div>
                            </div>
                            <textarea accesskey="r" class="form-control" cols="80" rows="8" name="comments"></textarea>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn cancel" data-dismiss="modal">
                            <?php _tt('Cancel', '取消')?>
                        </button>
                        <button type="button" class="btn save">
                            <?php _tt('Publish', '发布')?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
(function($){
    var jqMain = $('#comment-body'),
        jqCommentWindow = $('#comment-form-window'),
        jqForm = $('#comment-form');

    var commentService = $('#comment-body').commentServcie({
        loadUrl: '<?php echo $_context->getItemsUrl()?>',
        submitUrl: '<?php echo $_context->getSublimitUrl()?>',
        statusUpdateUrl: '<?php echo $_context->onSubmitExecUrl?>',
        totalElement: jqMain.find('.displayCount>em'),
        itemsElement: jqMain.find('#comment-items'),
        onSubmitAfter: function() {
            jqForm.find('[name=rating]').val('1');
            jqCommentWindow.find('button.close').trigger('click');
        },
    });

    $('#btn-begin-comment').click(function(){
        var isLogined = false;
        $.ajax({
            type: "get", 
            url: "<?php echo \Yii::$app->urlManager->createUrl('customer/account/check-login')?>", 
            cache:false, 
            async:false, 
            dataType: "json",
            success: function(status){
                isLogined = status;
                if(! status) {
                    window.location.href = "<?php echo \WS::$app->loginUrl?>?callback="+encodeURI(window.location.href);
                }
            },
        });
        return isLogined;
    });
})(jQuery);
</script>