<?php
    $_language = \WS::$app->language;
    $_googleMapKey = \WS::$app->params['googleMap']['key'];
    $_options = ['position'=>$this::POS_HEAD, 'depends' => '\module\page\assets\Asset'];

    $this->registerJsFile('http://maps.google.cn/maps/api/js?sensor=false&language='.$_language.'&key='.$_googleMapKey, $_options);
    $this->registerJsFile('/static/js/google.maps.js', ['depends' => [\module\page\assets\Asset::className()]]);
?>

<script type="text/javascript"> 
<?php $this->beginBlock('js_end') ?>
    var latlng = new google.maps.LatLng("<?php echo $data['latlng'][0]?>", "<?php echo $data['latlng'][1]?>");
    console.log($.fn.gmap3);
    var map = $('#google-map').gmap3({
        zoom: 12,
        center: latlng,
        panControl: false,
        scaleControl: false,
        mapTypeControl: false,
        streetViewControl:false,
        zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
        },
    });

    map.createMarker('default', latlng, {
        icon: '/static/img/house-maker.png'
    });

    map.displayCityPolygon(<?php echo json_encode($data['polygons'])?>);

<?php $this->endBlock()?>
</script>
<?php $this->registerJs($this->blocks['js_end'], $this::POS_END)?>

<div class="rets-view-block rets-around-view">
    <div class="map">
        <div id="google-map" style="height:400px"></div>
    </div>
</div>