<?php
    $_language = \WS::$app->language;
    $_googleMapKey = \WS::$app->params['googleMap']['key'];

    $this->registerJsFile('http://maps.google.cn/maps/api/js?sensor=false&language='.$_language.'&key='.$_googleMapKey);
    $this->registerJsFile('https://googlemaps.github.io/js-marker-clusterer/src/markerclusterer.js');
?>

<script type="text/javascript"> 
<?php $this->beginBlock('js_end') ?>
    var map = new google.maps.Map(document.getElementById("google-map"), {
        zoom: 15,
        center: new google.maps.LatLng(<?php echo $rets->latitude?>, <?php echo $rets->longitude?>),
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        panControl: false,
        scaleControl: false,
        mapTypeControl: false,
        streetViewControl:false,
        zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
        },
    });
    var marker = new google.maps.Marker({
        position: new google.maps.LatLng(<?php echo $rets->latitude?>, <?php echo $rets->longitude?>),
        map: map,
        draggable:false,
        animation: google.maps.Animation.DROP,
        icon: '/static/img/house-maker.png'
    });
<?php $this->endBlock()?>
</script>
<?php $this->registerJs($this->blocks['js_end'],\yii\web\View::POS_LOAD)?>

<div class="rets-view-block rets-around-view">
    <div class="map">
        <div id="google-map" style="height:400px"></div>
    </div>
</div>