<?php
    use module\estate\helpers\Rets as RetsHelper;
    use module\estate\helpers\RetsHtml;
    use module\estate\helpers\FieldFilter;
    use module\estate\helpers\FieldHtml;
?>
<div class="rets-view-block rets-recommend-view">
    <h2 class="block-heading"><?php _tt('Recommended houses', '相似房源推荐')?></h2>
    <div class="lay-g row house-grid">
        <?php foreach($nearbyHouses as $d):?>
            <div class="col lay-u-1-4">
                <div class="rets-item" style="margin-bottom:20px">
                    <div class="image-box" style="min-height:174px">
                        <a style="display:block;" href="<?php echo FieldFilter::viewUrl($d)?>" alt="<?php echo ''?>" target="_blank">
                            <div class="image-shower" style="background-image:url(<?php echo FieldFilter::photoUrl($d, 0, 300, 400)?>)"></div>
                        </a>
                        <span class="price"><?php echo FieldHtml::valueHtml($d['price'], 'money')?></span>
                    </div>
                    <div class="info">
                        <h2 class="location">
                            <span class="address"><?php echo $d['nm']?></span>
                        </h2>
                        <div class="info2">
                            <span class="left"><?php echo FieldHtml::valueHtml($d['prop'], 'housePropName')?></span>
                            <span class="right">
                              <?php if ($d['prop'] === 'LD'):?>
                                  <?php echo FieldHtml::valueHtml($d['lot_size'], 'square')?>
                              <?php else:?>
                                  <?php echo FieldHtml::valueHtml($d['square'], 'square')?>
                              <?php endif?>
                            </span>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        <?php endforeach?>
    </div>
</div>