<div class="rets-view-block rets-roi-view">
    <div class="block-heading">投资回报率</div>
    <table class="table-info">
        <tbody>
            <th>
                <td class="info-col">
                    <span>2.78%</span>
                    <label>投资回报(全款)</label>
                </td>
                <td class="info-col">
                    <span>3.68%</span>
                    <label>周边投资回报(全款)</label>
                </td>
                <td class="info-col">
                    <span>$43,163.00</span>
                    <label>年净收入预期(全款)</label>
                </td>
                <td class="info-col">
                    <span>$35,163.00</span>
                    <label>区域平均年净收入(全款)</label>
                </td>
            </th>
        </tbody>
    </table>
</div>