<style type="text/css">
.catalog-contact-banner {}
.catalog-contact-banner > li {padding:3px 0;color:#777;font-size:14px;}
.catalog-contact-banner > li > i.iconfont{display:inline-block;margin-right:5px;font-size:20px;vertical-align:middle;}
</style>
<ul class="catalog-contact-banner">
    <li><i class="iconfont icon-phone2"></i><?php echo $infos['cnPhoneNumber']?></span></li>
    <li><i class="iconfont icon-phone"></i><?php echo $infos['usPhoneNumber']?></span></li>
    <li><i class="iconfont icon-email"></i><?php echo $infos['email']?></span></li>
    <li><i class="iconfont icon-wexin"></i><?php echo $infos['wechat']?></span></li>
</ul>