<?php 
    $main = $result['main'];
?>
<div class="news-top-banner-container">
    <a class="news-item main"
        href="<?php echo $this->context->createNewUrl($main['url'])?>"
        target="_blank"
        style="background-image:url(<?php echo $main['image']?>);height:<?php echo $main['height']?>">
        <span><?php echo $main['title']?></span>
    </a>
    <div class="children-items">
        <div class="lay-g">
            <?php foreach($result['childrens'] as $children):?>
                <div class="lay-u-1-3">
                    <div class="box">
                        <a class="news-item sub" 
                            href="<?php echo $this->context->createNewUrl($children['url'])?>"
                            target="_blank"
                            style="background-image:url(<?php echo $children['image']?>);">
                            <span><?php echo $children['title']?></span>
                        </a>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    </div>
</div>
