<div class="home-top-yellowpages">
    <h2><?php _t('yellopage', 'PRO SERVICE')?></h2>
    <div class="desc"><?php _t('yellopage', 'Varieties of housing service companies provide you the service you need')?></div>
    <div class="lay-g groups">
        <?php foreach($groups as $group):?>
            <div class="lay-u-1-3">
                <div class="group">
                    <div class="heading"><a href="<?php echo $group['url']?>" target="_blank"><?php _t('yellopage', $group['name'])?></a></div>
                    <ul class="lay-g items">
                        <?php foreach($group['items'] as $_yellowpage):?>
                            <li class="lay-u-1-3">
                                <a class="item" href="/pro-service/<?php echo $_yellowpage->id?>/" target="_blank">
                                    <img class="yp-img" src="<?php echo $_yellowpage->getPhotoImageInstance()->resize(90, 90)?>">
                                    <div class="name"><?php echo $_yellowpage->name?></div>
                                    <div class="rating-box">
                                        <span class="rating"><span style="width:<?php echo $_yellowpage->rating * 20?>%"></span></span>
                                    </div>
                                </a>
                            </li>
                        <?php endforeach?>
                    </ul>
                </div>
            </div>
        <?php endforeach?>        
    </div>
</div>

