<?php 
    $this->registerJsFile('http://d3js.org/d3.v3.min.js', ['position'=>$this::POS_HEAD]);
?>

<div id="school-area-list">

    <?php foreach($items as $item):?>
    <div class="school-item">
        <div class="row-header">
            <div class="col col1">
                <span class="sa-no">
                    NO.<span><?php echo $item->sort_order?></span> <label>/<?php _tt('Rank', '排名')?></label>
                </span>
                <span class="sa-name-cn">
                    <?php if (\WS::$app->language === 'zh-CN'):?>
                        <?php echo $item->getItemData('name')[1]?>
                    <?php else:?>
                        <?php echo $item->getItemData('name')[0]?>
                    <?php endif?>
                </span>
                <span class="sa-name">
                    <?php if (\WS::$app->language === 'zh-CN'):?>
                        <?php echo $item->getItemData('name')[0]?>
                    <?php else:?>
                        <?php echo $item->getItemData('name')[1]?>
                    <?php endif?>
                </span>
                <span class="sa-rating">
                    <span class="rating"><span style="width:<?php echo $item->rating * 0.1 * 100?>%"></span></span>
                </span>
            </div>
            <div class="btn-links col col2 text-right">
                <a class="btn btn-primary" href="/school-district/<?php echo $item->id?>/">
                    <?php _tt('Details', '学区详情')?> <span class="iconfont icon-arraw-r"></span>
                </a>
                <div class="rets-links">
                    <?php if ($item->getSummary('total') > 0):?>
                        <a target="_blank" href="/house/purchase/school-district/sd-<?php echo str_replace('/', '%7C', strtolower($item->code))?>/">
                            <?php echo sprintf(tt('%d on Market', '共%d套在售'), $item->getSummary('total'))?>
                            <span class="iconfont icon-goto"></span>
                        </a>
                    <?php else:?>
                        <span class="invalid"><?php _tt('No property available', '暂无可售房源')?></span>
                    <?php endif?>
                </div>
            </div>
        </div><!--end header-->
        <div class="row-body">
            <div class="col col1">
                <a href="/school-district/<?php echo $item->id?>/">
                    <img src="<?php echo media_url('school-area/images')?>/<?php echo str_replace('/', '&', strtoupper($item->code))?>.jpg">
                </a>
            </div>
            <div class="col col2">
                <div class="avg-scores">
                    <div class="total"><label><?php _tt('SAT score', 'SAT平均分')?></label> <span><?php echo $item->sat->local[0]?></span></div>
                    <ul class="items">
                        <li class="item"><label><?php _tt('Reading', '阅读')?></label><span><?php echo $item->sat->local[1][0]?></span></li>
                        <li class="item"><label><?php _tt('Writing', '写作')?></label><span><?php echo $item->sat->local[1][1]?></span></li>
                        <li class="item"><label><?php _tt('Math', '数学')?></label><span><?php echo $item->sat->local[1][2]?></span></li>
                    </ul>
                </div>
                <div class="k12">
                    <h5>K12</h5>
                    <svg class="school-pie-chart" data-data="<?php echo implode(',', $this->context->k12($item->schools))?>" width="250" height="125"></svg>
                </div>
            </div>
            <div class="col col3 text-right">
                <table class="grid-info text-center">
                    <tr>
                        <td width="50%"><span><?php echo $item->special->special1?></span><?php _tt('Student number', '入学人数')?></td>
                        <td width="50%"><span>$<?php echo number_format($item->special->special3)?></span><?php _tt('Government subsidies', '人均政府补贴')?></td>
                    </tr>
                    <tr>
                        <td>
                            <?php if (\WS::$app->language === 'zh-CN'):?>
                                <span><?php echo number_format(floatval(str_replace(',', '', $item->getSummary('average-price'))) / 10000, 1)?>万美元</span>
                            <?php else:?>
                                <span>$<?php echo number_format($item->getSummary('average-price'), 0)?></span>
                            <?php endif?>
                            <?php _tt('Avg price', '平均房价')?>
                        </td>
                        <td>
                            <?php if (\WS::$app->language === 'zh-CN'):?>
                                <span><?php echo number_format($item->special->special2 / 10000, 1)?>万美元</span>
                            <?php else:?>
                                <span>$<?php echo number_format($item->special->special2)?></span>
                            <?php endif?>
                            <?php _tt('Avg income', '平均收入(年)')?>
                        </td>
                    </tr>
                </table>
                <div class="racists text-left">
                    <div class="header"><?php _tt('Racial distribution', '种族分布')?></div>
                    <ul>
                        <?php foreach (\module\schooldistrict\helpers\Racial::renderProcess($item->racials, 4) as $item):?>
                            <li style="width:<?php echo $item->width_value?>">
                                <div title="<?php echo $item->name.' '.$item->value?>" class="tooltip-lk bar bar-" style="background:<?php echo $item->bgColor?>;height:<?php echo $item->height?>;"></div>
                                <!--<label><?php echo $item->name?></label>-->
                            </li>
                        <?php endforeach?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endforeach?>
</div>
<script type="text/javascript">
window.createSchoolPie = function (ele, dataset) {
    var pie = d3.layout.pie();
    var arc = d3.svg.arc()  
        .innerRadius(40)  
        .outerRadius(60);
    var svg = d3.select(ele);
    var names = ['<?php _tt('High', '高中')?>', '<?php _tt('Middle', '初中')?>', '<?php _tt('Elementary', '小学')?>'];

    var tooltip = d3.select('body')  
        .append('div')  
        .attr('class', 'tooltip')  
        .style('opacity', 0.0);

    var arcs = svg.selectAll('g')  
        .data(pie(dataset))  
        .enter()  
        .append('g')
        .attr('transform', 'translate(160,65)')
        .attr('stroke', '#fff')
        .attr('stroke-width', 1.2)
        .on('mouseover', function (d, i) {
            d3.select(this).attr('stroke', colors[i]);
            tooltip.html(names[i] + ':' + dataset[i])
                .style('left', (d3.event.pageX) + 'px')  
                .style('top', (d3.event.pageY + 20) + 'px')  
                .style('opacity', 1.0);  
        })
        .on('mousemove', function (d, i) {
            tooltip.style("left", (d3.event.pageX) + "px")  
                .style("top", (d3.event.pageY + 20) + "px");
        })
        .on('mouseout', function () {
            d3.select(this).attr('stroke', '#fff');
            tooltip.style('opacity', 0.0);
        });

    var colors = ['#f66c6c', '#a3c9fb', '#99bd2a']; 

    arcs.append('path')  
        .attr('fill',function(d,i){  
            return colors[i];  
        })
        .attr('d',function(d){  
            return arc(d);
        });

    var legendGroup = svg.append('g')
        .attr('class', 'legend')
        .attr('transform', 'translate(0, 35)');

    var legendIems = legendGroup.selectAll('g.item')
        .data(dataset)
        .enter()
        .append('g')
        .attr('class', function(d, i){
            return 'item item-'+i;
        })
        .attr('transform', function (d, i) {
            return 'translate(0,' + (i * 24) + ')'
        });

        legendIems.append('rect')
            .style('width', '10px')
            .style('height', '14px')
            .style('rx', '3px')
            .style('ry', '3px')
            .style('fill', function(d, i){
                return colors[i];
            });

        var texts = legendIems.append('text')
            .attr('x', '15')
            .attr('y', '12');

        texts.append('tspan')
            .text(function(d, i){
                return names[i];
            });
};
(function($){
    $('#school-area-list .school-pie-chart').each(function(){
        var data = $(this).data('data').split(',');
        for(var i in data) {
            data[i] = parseInt(data[i]);
        }
        createSchoolPie(this, data);
    });
})(jQuery);
</script>