<?php
use module\estate\helpers\Rets as RetsHelper;
use module\estate\helpers\RetsHtml;
?>

<div class="house-grid">
    <div class="lay-g row">
        <?php foreach($items as $_rets):?>
            <?php
                $_entity = $_rets->entity();
                $_render = $_entity->render();
            ?>
            <div class="col lay-u-1-6">
                <div class="rets-item">
                    <div class="image-box">
                        <a href="<?php echo RetsHelper::getUrl($_entity)?>" target="_blank">
                            <div class="image-shower" style="background-image:url(<?php echo $_entity->getPhoto(0, 500, 500)?>)"></div>
                        </a>
                        <span class="price"><?php echo RetsHtml::getValueHtml($_entity, 'list_price')?></span>
                    </div>
                    <div class="info">
                        <h2 class="location">
                            <span class="address"><?php echo $_render->get('location')['value']?></span>
                        </h2>
                        <div class="rooms">
                            <span><?php echo $_render->get('rooms_descriptions')['value']?></span>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        <?php endforeach?>
    </div>
</div>