<?php
use module\estate\helpers\FieldFilter;
use module\estate\helpers\FieldHtml;
?>
<?php if (count($houses) > 0):?>
  <div class="hot-houses v-info-blk">
    <h2><?php _tt('Hot houses', '热门房源')?></h2>
    <div class="house-grid">
      <div class="lay-g row">
          <?php foreach($houses as $house):?>
            <div class="col lay-u-1-5" style="width:20%">
              <div class="rets-item" style="margin-bottom:20px">
                <div class="image-box" style="min-height:174px">
                  <a style="display:block;" href="<?php echo FieldFilter::viewUrl($house)?>" alt="<?php echo ''?>" target="_blank">
                    <div class="image-shower" style="background-image:url(<?php echo FieldFilter::photoUrl($house, 0, 300, 400)?>)"></div>
                  </a>
                  <span class="price"><?php echo FieldHtml::valueHtml($house['price'], 'money')?></span>
                </div>
                <div class="info">
                  <h2 class="location">
                    <span class="address"><?php echo $house['nm']?></span>
                  </h2>
                  <div class="info2">
                    <span class="left"><?php echo FieldHtml::valueHtml($house['prop'], 'housePropName')?></span>
                    <span class="right">
                              <?php if ($house['prop'] === 'LD'):?>
                                  <?php echo FieldHtml::valueHtml($house['lot_size'], 'square')?>
                              <?php else:?>
                                  <?php echo FieldHtml::valueHtml($house['square'], 'square')?>
                              <?php endif?>
                            </span>
                  </div>
                  <div class="clear"></div>
                </div>
              </div>
            </div>
          <?php endforeach?>
      </div>
    </div>
  </div>
<?php endif?>
