<?php 
    use yii\widgets\Block;
    use yii\bootstrap\Nav;
    use yii\bootstrap\NavBar;
    use yii\widgets\Breadcrumbs;
    use \module\page\widgets as PageWidget;
?>

<?php $this->beginContent('@module/page/views/layouts/base.phtml')?>

    <?php echo $content;?>

<div class="page-bottom-container">
    <?php echo PageWidget\FooterBefore::widget()?>
    <div class="container">
        <?php echo PageWidget\Footer::widget()?>
    </div>
</div>

<?php $this->endContent()?>