<?php
    use \module\page\widgets as PageWidget;


    $_options = ['position'=>$this::POS_HEAD, 'depends' => '\module\page\assets\Asset'];
    $this->registerCssFile('/static/css/layout-simple.css', $_options);

?>

<?php $this->beginContent('@module/page/views/layouts/base.phtml')?>

<nav id="main-nav">
    <img class="logo" src="<?php echo static_url('img/logo2.png')?>">
    <?php echo \module\page\widgets\Language::widget()?>
    <!--
    <a href="#" class="btn-link-rtn"><i class="iconfont icon-app"><?php _tt('Download App', '下载米乐居APP')?></i></a>
    -->
</nav>

<div id="main">
    <?php echo $content;?>
</div>

<?php echo PageWidget\Footer::widget()?>

<?php $this->endContent()?>