<?php
use module\estate\helpers\FieldFilter;
use module\estate\helpers\FieldHtml;
?>

<style type="text/css">
.home-top-houses .image-box {
    display:block;
}
.home-top-houses .image-box > .nm {
    font-size:0;
    text-indent:-1000px;
}
</style>

<div class="home-top-houses">
  <h2><?php _t('rets', 'LUXURY HOUSE')?></h2>
  <h3 class="desc">
      <?php _tt('Featuring luxury quality houses in '.\WS::$app->area->getName()[0], \WS::$app->area->getName()[1].'地区精品豪宅')?>
  </h3>
    <?php foreach($groups as $items):?>
        <div class="lay-g row">
            <?php foreach($items as $item):?>
                <?php
                    if (!isset($item['house'])) continue;
                    $_house = $item['house'];
                ?>
                <div class="col lay-u-<?php echo $item['col_rule']?>">
                    <div class="rets-item">
                        <a style="display:block;" href="<?php echo FieldFilter::viewUrl($_house)?>" target="_blank">
                            <span class="image-box lazy" data-src="<?php echo media_url($item['image'])?>">
                                <span class="nm"><?php echo $_house['nm']?></span>
                                <span class="price"><?php echo FieldHtml::valueHtml($_house['price'], 'money')?></span>
                            </span>
                        </a>
                        <div class="info">
                            <h2 class="location">
                                <span class="address"><?php echo $_house['nm']?></span>
                            </h2>
                            <div class="rooms">
                                <span><?php echo FieldHtml::valueHtml($_house['square'], 'square')?></span>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endforeach?>
</div>

<script>
<?php $this->beginBlock('home-top-header')?>
(function($){
    var $header = $('#header');
    var $window = $(window);
    $(window).scroll(function(){
        $header.css('background-position-y', '-' + ($window.scrollTop() * 0.2) + 'px');
    });
})(jQuery);
<?php $this->endBlock()?>
</script>

<?php $this->registerJs($this->blocks['home-top-header'], $this::POS_END)?>