<?php
$_yellowpage = $this->context->yellowpage;
$_imageHelper = $this->context->getImageHelper();
?>
<div id="yellow-media-gallery">
    <div class="picFocus">
        <div class="bd">
            <ul>
                <li>
                    <img src="<?php echo $_yellowpage->getPhotoImageInstance()->resize(235, 245)?>" style="height:230px"/>
                </li>
            </ul>
        </div>
    </div>
</div>
