<?php
$_context = $this->context;
?>
<div class="top-yellowpage-grid list-grid">
	<div class="grid">
		<?php foreach($_context->getItems() as $_item):?>
			<div class="col col-5">
				<div class="item">
					<div class="image-box">
						<a href="<?php echo $_context->createItemUrl($_item->id)?>">
							<img src="<?php echo $_item->getPhotoImageInstance()->resize(200, 267)?>" alt="<?php echo $_item->name?>" alt="<?php echo $_item->name?>">
						</a>
					</div>
					<div class="info-box">
						<div class="rating-box">
							<span class="rating"><span style="width:<?php echo $_item->rating * 20?>%"></span></span>
						</div>
						<div class="company-box">
							<a href="<?php echo $_context->createItemUrl($_item->id)?>"><?php echo $_item->name?></a>
						</div>
						<div class="contact-box">
							<label style="margin-right:3px;"><?php _tt('Business', '业务范围')?>:</label>
							<span><?php echo $_item->business?></span>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach?>
	</div>
</div>