<!-- JiaThis Button BEGIN -->
<div id="ckepop" style="margin-top:15px">
	<a class="jiathis_button_fb" title="Facebook"></a>
	<a class="jiathis_button_twitter" title="Twitter"></a>
	<a class="jiathis_button_googleplus" title="Google+"></a>
	<a class="jiathis_button_weixin" title="微信"></a>
	<a class="jiathis_button_qzone" title="QQ空间"></a>
	<a class="jiathis_button_tsina" title="新浪微博"></a>

	<script type="text/javascript">
		var jiathis_config = {
			url: window.location.href,
			pic: '<?php echo $this->context->rets->getPhotoUrl(600, 500)?>'
		};
	</script>

	<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1" charset="utf-8"></script>
</div> <!-- JiaThis Button END -->
