<?php
    $this->params['activeNavId'] = $type;
?>

<h1 class="none">
  <?php _tt(\WS::$app->area->getName())?> <?php _tt('BUY & SELL Search Result', '买房搜索结果, 按学区、按地铁, 地图搜房')?>    
</h1>

<?php echo \module\page\widgets\Nav::widget()?>

<div class="filters-container">
    <?php echo \module\estate\widgets\search\Filter::widget()?>
</div>

<div class="result-container">
    <div class="container">
        <?php echo \module\estate\widgets\search\Result::widget([
            'results' => $results
        ])?>
    </div>
</div>