<?php
    use \module\estate\widgets\view as ViewWidgets;
    use module\estate\helpers\RetsHtml;
?>

<style>
.base-information .attr-label {
    font-weight:200;
    color:#666;
}
.base-information .attr-label:after {
    content: ':';
}
</style>

<?php
    $this->params['activeNavId'] = $type;
?>

<?php echo \module\page\widgets\Nav::widget()?>

<div class="container mt20">
    <div class="lay-g">
        <div class="lay-u-5-6 pr20">
            <div class="lay-g" style="border-bottom: solid 1px #ddd;margin-bottom: 20px;">
                <div class="lay-u-1-2">
                    <?php echo ViewWidgets\Gallery::widget(['rets'=>$rets])?>
                </div>
                <div class="lay-u-1-2 pl20">
                    <div class="base-information">
                        <h1><?php echo $rets->getLocation()?></h1>
                        <?php if ($rets->prop_type === 'RN'):?>
                            <p class="price">
                                <span class="value"><?php echo RetsHtml::getValueHtml($rets, 'list_price')?></span>
                                <span class="value-addi">(约人民币<?php echo number_format($rets->list_price * 6.884)?>元)</span>
                            </p>
                        <?php else:?>
                            <p class="price">
                                <span class="value"><?php echo RetsHtml::getValueHtml($rets, 'list_price')?></span>
                                <span class="value-addi">(约人民币<?php echo number_format(intval($rets->list_price) * 6.9506 / 10000, 1)?>万)</span>
                            </p>
                        <?php endif?>
                        <ul class="fields">
                            <li class="field">
                                <?php echo RetsHtml::getFieldHtml($rets, 'prop_type_name')?>
                            </li>
                            <li class="field">
                                <?php $_type_id = strtolower($rets->prop_type).'_type_name';?>
                                <?php echo RetsHtml::getFieldHtml($rets, $_type_id)?>
                            </li>
                            <li class="field">
                                <?php echo RetsHtml::getFieldHtml($rets, 'no_bedrooms')?>
                            </li>
                            <li class="field-group">
                                <div class="lay-g">
                                    <div class="lay-u-1-2">
                                        <div class="field">
                                            <?php echo RetsHtml::getFieldHtml($rets, 'no_full_baths')?>
                                        </div>
                                    </div>
                                    <div class="lay-u-1-2">
                                        <div class="field">
                                            <?php echo RetsHtml::getFieldHtml($rets, 'no_half_baths')?>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="field">
                                <?php echo RetsHtml::getFieldHtml($rets, 'square_feet', ['title'=>'居住面积'])?>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo ViewWidgets\Roi::widget(['rets'=>$rets])?>
            <?php echo ViewWidgets\Detail::widget(['rets'=>$rets])?>
            <?php //echo ViewWidgets\Area::widget(['rets'=>$rets])?>
            <?php //echo ViewWidgets\PriceTrends::widget(['rets'=>$rets])?>
            <?php echo ViewWidgets\Around::widget(['rets'=>$rets])?>
            <?php echo ViewWidgets\Recommends::widget(['rets'=>$rets])?>
        </div>
        <div class="lay-u-1-6">
            <div class="right-side" style="background:#fff">
                <div class="side-box">
                    <div class="side-title"><?php _t('sys', 'Customer service')?></div>
                    <div class="side-content">
                        <?php echo \module\catalog\widgets\ContactBanner::widget()?>
                    </div>
                </div>
                <div class="side-box">
                    <div class="side-title"><?php _t('gour', 'Go Tour This House')?></div>
                    <div class="side-content">
                        <?php echo \module\gotour\widgets\Form::widget(['rets' => $rets])?>
                    </div>
                </div>
                <?php if ($rets->prop_type !== 'RN'):?>
                    <div class="side-box">
                        <div class="side-title"><?php _t('rets', 'Mortgage calculator')?></div>
                        <div class="side-content">
                            <?php echo \module\estate\widgets\detail\Calculator::widget(['rets' => $rets])?>
                        </div>
                    </div>
                <?php endif?>
            </div>
        </div>
    </div>
</div>