<?php
    use \module\estate\widgets\view as ViewWidgets;
    use module\estate\helpers\RetsHtml;
    use \module\estate\helpers\FieldFilter;
    use \module\estate\helpers\FieldHtml;
?>

<?php
    $this->params['activeNavId'] = $type;
?>

<?php echo \module\page\widgets\Nav::widget()?>

<script type="text/javascript" src="//static.bshare.cn/b/buttonLite.js"></script>
<script>
<?php $this->beginBlock('house-view-bshare')?>
bShare.addEntry({
    pic: "<?php echo FieldFilter::photoUrl($data, 0, 400, 330)?>"
});
<?php $this->endBlock()?>
</script>
<?php $this->registerJs($this->blocks['house-view-bshare'], $this::POS_END)?>

<div class="container mt20 prop-type-<?php echo strtolower($data['prop'])?>">
    <div class="lay-g">
        <div class="lay-u-5-6 pr20">
            <div class="lay-g" style="border-bottom: solid 1px #ddd;margin-bottom: 20px;">
                <div class="lay-u-1-2">
                    <?php echo ViewWidgets\Gallery::widget(['data'=>$data])?>
                </div>
                <div class="lay-u-1-2 pl20">
                    <div class="base-information">
                        <h1>
                            <?php echo $data['nm']?>
                            <a data-id="<?php echo $data['id']?>" class="btn-like<?php echo $data['liked'] ? ' active' : ''?>" href="javascript:void(0)" title="<?php _tt('Favorite', '收藏')?>">
                                <span class="iconfont icon-like_fill"></span>
                            </a>
                        </h1>
                        <div class="location">
                            <?php echo $data['loc']?>
                        </div>
                        <p class="price">
                          <span class="value"><?php echo FieldHtml::valueHtml(FieldFilter::money($data['price']))?></span>
                          <span class="value-addi">(约人民币<?php echo FieldHtml::valueHtml(FieldFilter::moneyRmb($data['price']))?>)</span>
                          <?php if ($data['prop'] !== 'RN'):?>
                            <span class="est-value">
                                <i class="iconfont icon-bi"></i>
                                <?php _tt('UStamite', '米乐居估价')?>&nbsp;<?php echo FieldHtml::valueHtml(FieldFilter::money($data['est_sale']))?>
                            </span>
                          <?php endif?>
                        </p>
                        <ul class="fields">
                            <li class="field">
                                <?php echo FieldHtml::render(
                                    FieldFilter::housePropName($data['prop']),
                                    tt('Property Type', '房屋类型'),
                                    'prop-type')?>
                            </li>
                            <?php if ($data['prop'] !== 'LD'):?>
                              <li class="field">
                                  <?php echo FieldHtml::render(
                                      $data['beds'],
                                      tt('Bed Rooms', '卧室数'),
                                      'beds')?>
                              </li>
                              <li class="field-group">
                                  <div class="lay-g">
                                      <div class="lay-u-1-2">
                                          <div class="field">
                                              <?php echo FieldHtml::render(
                                                  FieldFilter::unknown($data['baths'][0]),
                                                  tt('Full Baths', '全卫')
                                              )?>
                                          </div>
                                      </div>
                                      <div class="lay-u-1-2">
                                          <div class="field">
                                              <?php echo FieldHtml::render(
                                                  FieldFilter::unknown($data['baths'][1]),
                                                  tt('Half Baths', '半卫')
                                              )?>
                                          </div>
                                      </div>
                                  </div>
                              </li>
                            <?php endif?>
                            <li class="field">
                                <?php echo FieldHtml::render(
                                    FieldFilter::unknown($data['area']),
                                    tt('Area', '区域'))
                                ?>
                            </li>
                            <li class="field">
                                <?php if ($data['prop'] === 'LD'):?>
                                    <?php echo FieldHtml::render(
                                        FieldFilter::square($data['lot_size']),
                                        tt('Lot Size', '面积')
                                    )?>
                                    <div style="margin-bottom:60px"></div>
                                <?php else:?>
                                    <?php echo FieldHtml::render(
                                        FieldFilter::square($data['square']),
                                        tt('Living area', '居住面积')
                                    )?>
                                <?php endif?>
                            </li>
                            <li style="padding-top:8px">
                                <div class="bshare-custom">
                                    <div class="bsPromo bsPromo2"></div>
                                    <a title="分享到Facebook" class="bshare-facebook"></a>
                                    <a title="分享到Twitter" class="bshare-twitter"></a>
                                    <a title="分享到新浪微博" class="bshare-sinaminiblog"></a>
                                    <a title="分享到微信" class="bshare-weixin"></a>
                                    <a title="分享到QQ空间" class="bshare-qzone"></a>
                                </div>
                                <?php
                                    $this->registerJsFile('//static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=1&amp;lang=zh', ['position' => $this::POS_END]);
                                    $this->registerJsFile('//static.bshare.cn/b/bshareC0.js', ['position' => $this::POS_END]);
                                ?>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo ViewWidgets\Roi::widget(['data'=>$data['roi']])?>
            <?php echo ViewWidgets\Detail::widget(['data'=>$data['details']])?>
            <?php ////echo ViewWidgets\Area::widget(['rets'=>$rets])?>
            <?php ////echo ViewWidgets\PriceTrends::widget(['rets'=>$rets])?>
            <?php echo ViewWidgets\Around::widget(['data'=>$data])?>
            <?php echo ViewWidgets\Recommends::widget(['data'=>$data])?>
        </div>
        <div class="lay-u-1-6">
            <div class="right-side" style="background:#fff">
                <div class="side-box">
                    <h2 class="side-title"><?php _tt('Customer service', '米乐居客服')?></h2>
                    <div class="side-content">
                        <?php echo \module\catalog\widgets\ContactBanner::widget()?>
                    </div>
                </div>
                <div class="side-box">
                    <h2 class="side-title"><?php _t('tour', 'Go Tour This House')?></h2>
                    <div class="side-content">
                        <?php echo \module\gotour\widgets\Form::widget(['listNo' => $data['id']])?>
                    </div>
                </div>
                <?php if ($data['prop'] !== 'RN'):?>
                    <div class="side-box">
                        <h2 class="side-title"><?php _t('rets', 'Mortgage calculator')?></h2>
                        <div class="side-content">
                            <?php echo \module\estate\widgets\detail\Calculator::widget([
                                'price' => $data['price'],
                                'taxes' => $data['taxes']
                            ])?>
                        </div>
                    </div>
                <?php endif?>
            </div>
        </div>
    </div>
</div>

<script>
<?php $this->beginBlock('house-view') ?>
$('.base-information .btn-like').click(function (event) {
    if (document.getElementById('login-status').getAttribute('content') === 'false') {
        window.location.href = document.getElementById('login-url').getAttribute('content') + '?callback=' + encodeURI(window.location.href);
        return;
    }

    var $that = $(this),
        id = $that.data('id'),
        isActived = $that.hasClass('active');

    var updateUrl = "<?php echo \Yii::$app->urlManager->createUrl('customer/rets-favorite/update')?>";
    $.get(updateUrl + '?list_no='+id, {}, function (result) {
        if (result) {
            if (isActived) {
                $that.removeClass('active');
            } else {
                $that.addClass('active');
            }
        }
    }, 'json');
});
<?php $this->endBlock()?>
</script>
<?php $this->registerJs($this->blocks['house-view'], $this::POS_END)?>