<div id="footer-before" class="page-footer-before">
    <div class="container">
        <div class="lay-g">
            <div class="lay-u-1-3">
                <div class="contacts">
                    <div class="heading"><?php _t('footer', 'You may contact us')?></div>
                    <div class="cn-phone"><span class="icon2"></span>13167111930</div>
                    <div class="us-phone"><span class="icon2"></span>857-205-4318</div>
                    <div class="email"><span class="icon2"></span>master@wesnail.com</div>
                </div>
            </div>
            <div class="lay-u-1-3">
                <div class="about">
                    <div class="heading"><?php _t('footer', 'Follow us')?></div>
                    <div class="item follow">
                        <a href="javascript:void(0)"><i class="iconfont icon-wechat"></i></a>
                        <a href="javascript:void(0)"><i class="iconfont icon-weibo"></i></a>
                    </div>
                    <div class="item">
                        <a href="#"><i class="iconfont icon-sitemap" style="margin-right:3px"></i><?php _t('footer', 'Site Map')?></a>
                    </div>
                </div>
            </div>
            <div class="lay-u-1-3">
                <div class="app">
                    <div class="lay-t">
                        <div class="lay-col" style="width:1%">
                            <div class="qrcode"></div>
                        </div>
                        <div class="lay-col content">
                            <?php _t('footer', 'Download <br/>USLEJU APP')?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>