<div id="footer-before" class="page-footer-before">
    <div class="container">
        <div class="lay-g">
            <div class="lay-u-1-3">
                <div class="contacts">
                    <div class="heading"><span class="icon-circle"></span>You may contact us:</div>
                    <div class="cn-phone"><span class="icon2"></span>13167111930</div>
                    <div class="us-phone"><span class="icon2"></span>857-205-4318</div>
                    <div class="email"><span class="icon2"></span>master@wesnail.com</div>
                </div>
            </div>
            <div class="lay-u-1-3">
                <div class="about">
                    <div class="item"><span class="icon-circle"></span>About Wesnail</div>
                    <div class="item"><span class="icon-circle"></span>Join us</div>
                    <div class="item"><span class="icon-circle"></span>Follow Wesnail
                        <div class="follow">
                            <span class="iconfont icon-wx"></span>
                            <span class="iconfont icon-weibo"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="lay-u-1-3">
                <div class="other">
                    <div class="item"><span class="icon-circle"></span>Help</div>
                    <div class="item"><span class="icon-circle"></span>Terms & Privacy</div>
                    <div class="item"><span class="icon-circle"></span>Policies</div>
                    <div class="apps">
                        <div class="android">App for Android</div>
                        <div class="ios">App for IOS</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>