<?php
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

$urlManager = \WS::$app->urlManager;
$currentUrl = \WS::$app->request->getHostInfo().\WS::$app->request->url;
?>
<nav id="main-nav">
    <?php $_actionNavId = isset($this->params['activeNavId']) ? $this->params['activeNavId'] : null;?>
    <div class="menubar">
        <div class="container">
            <?php if(\WS::share('isHome')):?>
                <h1 class="logo">
                    <a href="/" title="北美房产一网打尽">
                        <?php
                            $_areaName = \WS::$app->area->getName();
                        ?>
                        <img src="<?php echo static_url('rets/img/logo.png')?>" alt="<?php _tt($_areaName[0].' USLEJU', $_areaName[1].'米乐居')?>">
                    </a>
                </h1>
            <?php else:?>
                <div class="logo">
                    <a href="/" title="北美房产一网打尽">
                        <?php
                            $_areaName = \WS::$app->area->getName();
                        ?>
                        <img src="<?php echo static_url('rets/img/logo.png')?>" alt="<?php _tt($_areaName[0].' USLEJU', $_areaName[1].'米乐居')?>">
                    </a>
                </div>
            <?php endif?>
            <?php if (WS::$app->controller->module->id.'-'.WS::$app->controller->id.'-'.WS::$app->controller->action->id === 'home-default-index'):?>
                <a href="http://www<?php echo domain()?>/" class="area-switcher-btn" href="javascript:void(0)">
                    <i class="iconfont icon-area"></i><?php echo tt(\WS::$app->area->getName())?>
                </a>
            <?php endif?>
            <?php 
                $_menuItems = [
                    [
                        'label' => t('app/nav', 'BUY & SELL'),
                        'url' => '/house/purchase/',
                        'active'=>$_actionNavId === 'purchase'
                    ],
                    [
                        'label' => t('app/nav', 'SCHOLL DISTRICTSS'),
                        'url' => ['/schooldistrict/default/index'],
                        'active'=>$_actionNavId === 'school-district',
                        'disabled' => \WS::$app->area->id !== 'ma'
                    ],
                    [
                        'label' => t('app/nav', 'RENTAL'),
                        'url' => '/house/lease/',
                        'active'=>$_actionNavId === 'lease'],
                    [
                        'label' => t('app/nav', 'PRO SERVICE'),
                        'url' => ['/yellowpage/default/index'],
                        'active'=>$_actionNavId === 'yellowpage'
                    ],
                    [
                        'label' => t('app/nav', 'NEWS'),
                        'url' => ['/news/default/index'],
                        'active'=>$_actionNavId === 'news'
                    ]
                ];
            ?>
            <ul class="menu-items">
                <?php foreach($_menuItems as $_item):?>
                    <?php if (!array_get($_item, 'disabled', false)):?>
                    <li class="menu-item <?php echo $_item['active'] ? 'active' : ''?> <?php echo isset($_item['class']) ? $_item['class'] : ''?>">
                        <a class="menu-link" href="<?php echo $urlManager->createUrl($_item['url'])?>"><?php echo $_item['label']?></a>
                    </li>
                    <?php endif?>
                <?php endforeach?>
            </ul>
            <div class="quick-links">
                <?php if (WS::$app->user->isGuest):?>
                    <a class="quick-link" href="<?php echo \WS::$app->loginUrl?>?callback=<?php echo urlencode($currentUrl)?>"><span class="iconfont icon-login"><?php _tt('LOGIN','登陆')?></a>
                <?php else:?>
                    <div class="my-account">
                        <a href="<?php echo \WS::$app->memberUrl?>umember/profile/" class="quick-link" style="margin-left:0">
                            <span class="iconfont icon-login">
                                <?php echo WS::$app->user->getIdentity()->getName()?>
                            </span>
                        </a>
                        <ul class="my-account-menu" style="position: absolute;">
                            <li><a href="<?php echo \WS::$app->memberUrl?>"><?php _tt('Member Center', '会员中心')?></a></li>
                            <li style="border-bottom-width:0"><a href="<?php echo \WS::$app->logoutUrl?>?callback=<?php echo urlencode($currentUrl)?>"><?php _tt('Logout', '登出')?></a></li>
                        </ul>
                    </div>
                <?php endif?>
                <?php echo \module\page\widgets\Language::widget()?>
            </div>
        </div>
    </div>
</nav>

<div class="clear"></div>