<?php
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

$urlManager = \WS::$app->urlManager;
?>
<nav id="main-nav">
    <?php $_actionNavId = isset($this->params['activeNavId']) ? $this->params['activeNavId'] : null;?>
    <div class="menubar">
        <div class="container">
            <div class="logo">
                <a href="/" title="北美房产一网打尽" alt="北美房产一网打尽"><img src="/static/img/logo.png" alt="<?php _tt('USLEJU', '米乐居')?>"></a>
            </div>
            <?php if (WS::$app->controller->module->id.'-'.WS::$app->controller->id.'-'.WS::$app->controller->action->id === 'home-default-index'):?>
                <a href="http://www<?php echo domain()?>/" class="area-switcher-btn" href="javascript:void(0)">
                    <i class="iconfont icon-area"></i><?php _t('city', 'Boston')?>
                </a>
            <?php endif?>
            <?php 
                $_menuItems = [
                    ['label' => t('app/nav', 'BUY & SELL'), 'url' => '/house/purchase/', 'active'=>$_actionNavId === 'purchase'],
                    ['label' => t('app/nav', 'SCHOLL DISTRICTSS'), 'url' => ['/schooldistrict/default/index'], 'active'=>$_actionNavId === 'schooldistrict'],
                    ['label' => t('app/nav', 'RENTAL'), 'url' => '/house/lease/', 'active'=>$_actionNavId === 'lease'],
                    ['label' => t('app/nav', 'PRO SERVICE'), 'url' => ['/yellowpage/default/index'], 'active'=>$_actionNavId === 'yellowpage'],
                    ['label' => t('app/nav', 'NEWS'), 'url' => ['/news/default/index'], 'active'=>$_actionNavId === 'news']
                ];
            ?>
            <ul class="menu-items">
                <?php foreach($_menuItems as $_item):?>
                    <li class="menu-item <?php echo $_item['active'] ? 'active' : ''?> <?php echo isset($_item['class']) ? $_item['class'] : ''?>">
                        <a class="menu-link" href="<?php echo $urlManager->createUrl($_item['url'])?>"><?php echo $_item['label']?></a>
                    </li>
                <?php endforeach?>
            </ul>
            <div class="quick-links">
                <?php if (WS::$app->user->isGuest):?>
                    <a class="quick-link" href="<?php echo \WS::$app->loginUrl?>"><span class="iconfont icon-login"><?php _tt('LOGIN','登陆')?></a>
                <?php else:?>
                    <div class="my-account">
                        <a href="<?php echo \WS::$app->memberUrl?>umember/profile/" class="quick-link" style="margin-left:0">
                            <span class="iconfont icon-login">
                                <?php echo WS::$app->user->getIdentity()->username?>
                            </span>
                        </a>
                        <ul class="my-account-menu" style="position: absolute;">
                            <li><a href="<?php echo \WS::$app->memberUrl?>"><?php _tt('Member Center', '会员中心')?></a></li>
                            <li style="border-bottom-width:0"><a href="<?php echo \WS::$app->logoutUrl?>"><?php _tt('Logout', '登出')?></a></li>
                        </ul>
                    </div>
                <?php endif?>
                <!--
                <a class="quick-link" href="#"><span class="iconfont icon-message"></span>MESSAGES</a>
                <a class="quick-link" href="#"><span class="iconfont icon-help"></span>HELP</a>
                -->
                <?php echo \module\page\widgets\Language::widget()?>
                <!--
                <?php if (\WS::$app->language === 'en-US'):?>
                    <a class="quick-link" href="/language/zh-CN/"><span class="iconfont icon-chinese"></span>中文</a>
                <?php else:?>
                    <a class="quick-link" href="/language/en-US/"><span class="iconfont icon-english"></span>English</a>
                <?php endif?>-->
            </div>
        </div>
    </div>
</nav>

<div style="float:none;clear:both;"></div>