<!--基础脚本准备-->
<?php
    $_googleMapSdk = 'http://maps.google.cn/maps/api/js?sensor=false&language=en-US&key=AIzaSyAKfreY6Rf9fOvsJNcxGMsPPNHpXbvj6wo';
    $this->registerJsFile($_googleMapSdk, ['position'=>$this::POS_HEAD]);
    $this->registerJsFile('/static/map/lib/markerclusterer.js', ['position'=>$this::POS_HEAD]);
    // $this->registerJsFile('/static/map/lib/StyledMarker.js', ['position'=>$this::POS_HEAD]);
    $this->registerJsFile('/static/map/lib/HouseMarker.js', ['position'=>$this::POS_HEAD]);
    
    $this->registerJsFile('/static/lib/vue.min.js',  ['position'=>$this::POS_HEAD]);
?>

<!--主体-->
<div id="map-app">
    <vc-loading></vc-loading>
    <vc-nav id="nav"></vc-nav>
    <vc-side-panel id="side-panel"></vc-side-panel>
    <vc-map id="map"></vc-map>
    <vc-return></vc-return>
</div>

<!--组件: 地图-->
<script type="text/x-template" id="template-map">
    <div class="gmap"></div>
</script>

<!--组件: 左侧导航-->
<script type="text/x-template" id="template-nav">
    <ul class="gmap-nav">
        <li v-for="(item, menuId) in menuItems" :class="{'active': current == menuId}" v-if="!item.hide">
            <a href="javascript:void(0)" v-on:click="switchMenu(menuId)">
                <i class="iconfont" :class="item.icon"></i>
                {{ item.text }}
            </a>
        </li>
    </ul>
</script>

<!--组件: 操作面板-->
<script type="text/x-template" id="template-side_panel">
    <div class="gmap-panel">
        <div class="panel-container">
            <vc-search v-model="q" v-show="isInMode('areas')" class="area-search"></vc-search>
            <vc-schools v-model="schoolId" v-show="isInMode('schools')" class="gmap-schools"></vc-schools>
            <vc-subwaies v-model="subway" v-show="isInMode('subwaies')" class="gmap-subwaies"></vc-subwaies>
            <vc-filters v-model="filters" ref="filters"></vc-filters>
        </div>
    </div>
</script>

<!--组件: 搜索框-->
<script type="text/x-template" id="template-search">
    <div class="search-input-box">
        <div class="heading" style="padding:10px;">
            <div class="typeahead__container">
                <div class="search-input-group input-group">
                    <div class="input-box">
                        <span class="iconfont icon-search"></span>
                        <input
                            id="q-input"
                            autocomplete="off"
                            type="search" 
                            name="q"
                            v-model="q"
                            class="form-control search-input" 
                            autocomplete="off"
                            placeholder="<?php echo WS::text(['en-US'=>'Search City, Zip code, List No', 'zh-CN'=>'搜索城市，邮编，房源号'])?>">
                    </div>
                    <span class="typeahead__button">
                        <a id="go" @click="handleConfirm()" href="javascript:void(0)"><?php echo t('search', 'SEARCH')?></a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</script>

<!--筛选-->
<script type="text/x-template" id="template-filters">
    <div class="gmap-filters-container">
        <ul class="gmap-filters">
            <li v-for="(filter, filterId) in items" class="filter">
                <label>{{ filter.title }}</label>
                <ul class="optoins">
                    <li class="option" 
                        :class="{active: getItemIsActive(filterId)}"
                        @click="clearItemActive(filterId)">不限</li>
                    <li v-for="(text, id) in filter.options" 
                        class="option" 
                        :class="{active: getItemIsActive(filterId, id)}"
                        @click="setItemActive(filterId, id)">{{ text }}</li>
                    <!--<vc-range-input v-if="filter.custom" v-model="data.customs[filterId]"></vc-range-input>-->
                </ul>
            </li>
        </ul>
        <div class="text-right">
            <a href="javascript:void(0)" @click="clearAll()">清空所选</a>
        </div>
    </div>
</script>

<!--学区选择弹-->
<script type="text/x-template" id="template-schools">
    <div class="gmap-schools">
        <div class="heading">
            <span v-if="school">选择学区: {{ school.name}}</span>
            <div class="ft">
                <button @click="handleSelect()" class="btn red fill">选择学区</button>
            </div>
        </div>
        <vc-schools-popup></vc-schools-popup>
    </div>
</script>

<!--学区选择弹出框-->
<script type="text/x-template" id="template-school-popup">
    <div class="gmap-panel-popup gmap-school-popup" v-if="visible">
        <h2>请选择学区</h2>
        <ul class="list">
            <li class="school-item" v-for="(item, id) in items" :class="{active:getIsActive(id)}">
                <a href="javascript:void(0)" @click="handleChanged(item)">{{ item.name }}</a>
            </li>
        </ul>
    </div>
</script>

<!--地铁选择-->
<script type="text/x-template" id="template-subwaies">
    <div class="gmap-subwaies">
        <div class="heading">
            <span v-if="line">地铁线: {{ line.name }} ({{ stations.length }}个站点)</span>
            <span v-if="!line">请选择地铁线</span>
            <div class="ft">
                <button @click="handleSelect()" class="btn red fill">选择地铁</button>
            </div>
        </div>
        <vc-subwaies-popup></vc-subwaies-popup>
    </div>
</script>

<!--地铁选择弹出框-->
<script type="text/x-template" id="template-subway-popup">
    <div class="gmap-panel-popup gmap-subway-popup" v-if="visible">
        <h2>请选择地铁线</h2>
        <ul>
            <li class="subway-line" 
                v-for="line in items"
                :class="{active: isActiveLine(line)}" 
                :style="{borderLeftColor: line.bgcolor}">
                <a href="javascript:void(0)">{{ line.name }}</a>
                <div class="stations">
                    <ul class="groups">
                        <li v-for="stations in groupStations(line.stations)" class="group">
                            <ul class="list">
                                <li v-for="station in stations" @click="handleSelect(line, station)" :class="{active: isActiveStation(station)}">
                                    {{station.name}}
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <div class="actions">
                        <div class="link-btns">
                            <a class="link-btn" @click="handleSelectAll(line)">全选</a>
                            <a class="link-btn" @click="handleClearAll(line)">清除</a>
                        </div>
                        <button class="btn btn-primary btn-ok" @click="handleConfirm()">确定</button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</script>

<!--组件: 房源结果-->
<script type="text/x-template" id="template-results">
    <div class="gmap-results">
        <div class="result-count">共<span>3266</span>套房源</div>
        <div class="result-list">
            <div class="item" v-for="item in items">
                <div class="cols">
                    <div class="image-col">
                        <div class="image-shower" :style="'background-image:url(http://media.mlspin.com/Photo.aspx?mls='+item.id+'&n=0&w=550&height=550)'"></div>
                        <div class="property-type">多家庭独栋</div>
                    </div>
                    <div class="info-col">
                        <div class="location">50 Percy RD, Lexington, MA 02421</div>
                        <div class="general">
                            卧室 10 | 全卫 2 半卫 1
                        </div>
                        <div class="price">
                            <span>$79.60</span>万
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<!--组件: 房源结果-->
<script type="text/x-template" id="template-loading">
    <div v-if="visible" style="position:fixed;left:0;right:0;top:0;bottom:0;background:rgba(0,0,0,.25);z-index:9999999;">
        <div class="gmap-loading">
            <img src="/static/img/loading0.gif"/> 正在载入，请稍候...
        </div>
    </div>
</script>

<!--组件: 房源结果-->
<script type="text/x-template" id="template-return">
    <a id="btn-return" class="btn red" :href="href"><i class="iconfont icon-switch"></i> 返回到列表</a>
</script>

<!--样式-->
<style type="text/css">
    <?php $this->beginBlock('mapcss') ?>
        <?php include(__DIR__.'/index.css')?>
    <?php $this->endBlock() ?>
</style>
<?php $this->registerCss($this->blocks['mapcss'], ['position'=>$this::POS_HEAD])?> 

<!--应用载入-->
<script type="text/javascript">
window.$viewData = {
    type: <?php echo json_encode($type)?>,
    dicts: <?php echo json_encode($dicts)?>,
};

</script>
<?php
    $this->registerJsFile('/static/map/require.js');

    $this->registerJsFile('/static/map/app/nav.js');

    $this->registerJsFile('/static/map/app/side-panel/search.js');
    $this->registerJsFile('/static/map/app/side-panel/filters.js');
    $this->registerJsFile('/static/map/app/side-panel/subwaies.js');
    $this->registerJsFile('/static/map/app/side-panel/schools.js');
    $this->registerJsFile('/static/map/app/side.panel.js');

    $this->registerJsFile('/static/map/lib/google.map.util.js');

    $this->registerJsFile('/static/map/app/map/house.detail.js');
    $this->registerJsFile('/static/map/app/map.js');
    
    $this->registerJsFile('/static/map/app.js');
?>