<ul class="dropdown-filters">
    <?php foreach($rules as $ruleId => $rule):?>
        <li class="filter dropdown filter-<?php echo $ruleId?>">
            <label>
                <?php echo $rule['heading']?>
                <span><?php echo $this->context->getSelectName($ruleId)?></span>
                <i class="arrow"></i>
            </label>
            <ul class="dropdown-options">
                <?php foreach($rule['options'] as $key=>$item):?>
                    <?php list($value, $name) = $item;?>
                    <li>
                        <a href="<?php echo $this->context->createUrl($ruleId, $value)?>"><?php echo $name?></a> 
                    </li>
                <?php endforeach?>
            </ul>
        </li>
    <?php endforeach?>
</ul>