<div class="search-content inline-block text-center">
    <ul class="type-tab">
        <?php foreach($types as $type):?>
            <li class="type-item <?php echo $type['active'] ? 'active' : ''?>" ref="#tab-content-<?php echo $type['id']?>">
                <a class="type-item-link"><?php echo t('app/nav', $type['name'])?></a>
            </li>
        <?php endforeach?>
    </ul>
    <?php foreach($types as $type):?>
        <div class="tab-content <?php echo $type['active'] ? 'active' : ''?>" id="tab-content-<?php echo $type['id']?>">
            <?php
                echo \module\estate\widgets\search\Input::widget([
                    'id'=>$type['id'],
                    'resultUrl'=>$type['resultUrl'],
                    'type' => $type['type']
                ])
            ?>
        </div>
    <?php endforeach?>
</div>

<script>
<?php $this->beginBlock('search-input-all') ?>
  var $tabLi = $('.search-content .type-item');
  var $tabCn = $('.search-content .tab-content');
  $(function(){
    $tabLi.on('click', function () {
      $tabLi.filter('.active').removeClass('active');
      $(this).addClass('active');

      var ref = $(this).attr('ref');
      $tabCn.filter('.active').removeClass('active');
      $(ref).addClass('active');
    });
  });
<?php $this->endBlock(); ?>
</script>

<?php $this->registerJs($this->blocks['search-input-all'], $this::POS_END)?>
