<div class="search-content inline-block text-center">
    <ul class="type-tab">
        <?php foreach($types as $_options):?>
            <li class="type-item <?php echo $_options['active'] ? 'active' : ''?>" ref="#tab-content-<?php echo $_options['id']?>">
                <a class="type-item-link"><?php echo t('app/nav', $_options['name'])?></a>
            </li>
        <?php endforeach?>
    </ul>
    <?php foreach($types as $_options):?>
        <div class="tab-content <?php echo $_options['active'] ? 'active' : ''?>" id="tab-content-<?php echo $_options['id']?>">
            <?php
                echo \module\estate\widgets\search\Input::widget([
                    'id'=>$_options['id'],
                    'resultUrl'=>$_options['resultUrl']
                ])
            ?>
        </div>
    <?php endforeach?>
</div>

<script>
<?php $this->beginBlock('search-input-all') ?>
  var $tabLi = $('.search-content .type-item');
  var $tabCn = $('.search-content .tab-content');
  $(function(){
    $tabLi.on('click', function () {
      $tabLi.filter('.active').removeClass('active');
      $(this).addClass('active');

      var ref = $(this).attr('ref');
      $tabCn.filter('.active').removeClass('active');
      $(ref).addClass('active');
    });
  });
<?php $this->endBlock(); ?>
</script>

<?php $this->registerJs($this->blocks['search-input-all'], $this::POS_END)?>
