<?php
// http://www.runningcoder.org/jquerytypeahead/demo/?user_v1%5Bquery%5D=as
?>
<div class="search-content inline-block text-center">
    <form id="form-search" name="form-search" action="<?php echo $resultUrl?>">
        <div class="typeahead__container">
            <div class="search-input-group input-group">
                <span class="iconfont icon-search"></span>
                <input id="<?php echo $id?>"
                    autocomplete="off"
                    type="search" 
                    name="q" 
                    class="form-control search-input" 
                    autocomplete="off"
                    placeholder="<?php echo WS::text(['en-US'=>'Search City, Zip code, Address, List No', 'zh-CN'=>'搜索城市，邮编，地址，房源号'])?>" 
                    value="<?php echo $q?>">
                <span class="typeahead__button">
                    <a id="go" href="javascript:void(0)"><?php echo t('search', 'SEARCH')?></a>
                </span>
            </div>
        </div>
    </form>
</div>
<script>
$('#go').on('click', function(){
    $(this).parents('form').submit();
    return false;
});
$('#form-search').submit(function(){
    var qValue = $(this).find('input').val();
    var goUrl = '<?php echo $resultUrl?>';
    if (qValue && qValue !== '') {
        qValue = qValue.replace(/[^A-Za-z0-9\s]+/g, ' ');
        goUrl += 'q-' + qValue + '/';
    }
    window.location.href = goUrl
    
    return false;
});

$.typeahead({
    input: '#<?php echo $id?>',
    minLength: 1,
    delay: 500,
    order: "desc",
    source: {
        city: {
            display: "name",
            href: "<?php echo $resultUrl?>q-{{name|slugify}}/",
            ajax: {
                url: '/estate/autocomplete/',
                path: "cities"
            }
        }
    },
    template: function (query, item) {
        return "{{name}} <small style='color:#999;'>{{type}}</small>";
    },
    callback: {
        onClickAfter: function (node, a, item, event) {
            window.location.href = item.href
        }
    }
})
</script>