<?php
    $goUrlEndChars = \WS::$app->language === 'zh-CN' ? '/zh/' : '/';
?>
<div class="container area-container">
    <h2><?php _tt('Choose location', '请选择区域')?></h2>
    <div class="area-blocks lay-g">
        <div class="area-block-col lay-u-1-2">
            <a href="//ma<?php echo domain().$goUrlEndChars?>" class="image-btn image-btn-h1" style="background-image:url(<?php echo media_url('area/ma.jpg')?>)">
                <span>
                    <?php _tt('Boston', '波士顿')?>
                    <i>(<?php _tt('Massachusetts', '马萨诸塞州')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-2">
            <a href="//ny<?php echo domain().$goUrlEndChars?>" class="image-btn image-btn-h1" style="background-image:url(<?php echo media_url('area/ny.jpg')?>)">
                <span>
                    <?php _tt('New York', '纽约')?>
                    <!--<i>(<?php _tt('New York', '纽约')?>)</i>-->
                </span>
            </a>
        </div>
    </div>
    <div class="area-blocks lay-g" style="margin-top:15px">
        <div class="area-block-col lay-u-1-3">
            <a href="//ga<?php echo domain().$goUrlEndChars?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/ga.jpg')?>)">
                <span>
                    <?php _tt('Atlanta', '亚特兰大')?>
                    <i>(<?php _tt('Georgia', '佐治亚州')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-3">
            <a href="//ca<?php echo domain().$goUrlEndChars?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/ca.jpg')?>)">
                <span>
                    <?php _tt('Los Angel', '洛杉矶')?>
                    <i>(<?php _tt('California', '加利福尼亚')?>)</i>
                </span>
            </a>
        </div>
        <div class="area-block-col lay-u-1-3">
            <a href="//il<?php echo domain().$goUrlEndChars?>" class="image-btn image-btn-h2" style="background-image:url(<?php echo media_url('area/il.jpg')?>)">
                <span>
                    <?php _tt('Chicago', '芝加哥')?>
                    <i>(<?php _tt('Illinois', '伊利诺斯')?>)</i>
                </span>
            </a>
        </div>
    </div>
</div>