<div class="marketing-guarantee mt30">
    <div class="container">
        <div class="lay-g">
            <?php foreach($items as $_className=>$_item):?>
                <?php $_info = isset($_item[\Yii::$app->language]) ? $_item[\Yii::$app->language] : $_item['en-US'];?>
                <div class="lay-u-1-4 item <?php echo $_className?>">
                    <div class="icon"></div>
                    <div class="heading"><?php echo $_info['heading']?></div>
                    <div class="info"><?php echo $_info['info']?></div>
                </div>
            <?php endforeach?>
        </div>
    </div>
</div>
