<?php
$_context = $this->context;
$_totals = $_context->totals();
?>
<div class="search-box">
  <h1 class="heading"><?php echo t('rets', 'FIND YOUR HOME')?></h1>
  <h2 class="totals">
      <?php if(\WS::$app->language === 'zh-CN'):?>
          <?php echo \WS::$app->area->getName()[1]?>真实 售房<span><?php  echo $_totals[0]?></span>套, 租房<span><?php  echo $_totals[1]?></span>套
      <?php else:?>
        ON MARKET FOR SELL <span><?php  echo $_totals[0]?></span>, FOR RENT <span><?php  echo $_totals[1]?></span>
      <?php endif?>
  </h2>
    <?php echo \module\estate\widgets\search\InputAll::widget()?>
</div>