<?php
use \module\page\widgets\Nav as MenuNav;
use \module\schooldistrict\widgets\Grid as SchoolDistrictGrid;

$this->params['activeNavId'] = 'schooldistrict';
?>

<div id="header">
    <div class="img-mask">
        <?php echo MenuNav::widget()?>
        <div class="info1">&nbsp;</div>
        <div class="school-area-info">
            <div class="info1">麻省排名前<?php echo $summary['count']?>的顶级公立学区</div>
            <div class="info2"><?php echo $summary['total']?>套在售房源</div>
        </div>
    </div>
</div>

<div class="container">
    <?php
        echo SchoolDistrictGrid::widget();
    ?>
</div>