<?php
use \module\page\widgets\Nav as MenuNav;
use \module\schooldistrict\widgets\Grid as SchoolDistrictGrid;

$this->params['activeNavId'] = 'schooldistrict';
?>

<div id="header">
    <div class="img-mask">
        <?php echo MenuNav::widget()?>
        <div class="info1">&nbsp;</div>
        <div class="school-area-info">
            <div class="info1">
                <?php echo sprintf(
                    tt('Top %s Public School Districts in Massachusetts', '麻省排名前%s的顶级公立学区'),
                    $summary['count']
                )?>
            </div>
            <div class="info2">
                <?php echo sprintf(tt('%s on market', '%s套在售房源'), $summary['total'])?>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <?php
        echo SchoolDistrictGrid::widget();
    ?>
</div>