<?php
    $this->params['activeNavId'] = 'schooldistrict';
?>

<style type="text/css">
#base-info-container .base-info {
    position:relative;
}
#base-info-container .base-info .houses-go {
    position:absolute;
    top:0;right:0;
}
.go-houses-btn, .go-houses-btn:focus {
    display: inline-block;
    color: #f15044;
    border: solid 1px #f15044;
    padding: 5px 8px;
    font-size: 14px
}
.go-houses-btn:hover {
    border: solid 1px #f00;
    color: #f00;
}
.houses-go .invalid {
    display:inline-block;
    color: #999;
    border: solid 1px #999;
    padding: 3px;
}
</style>

<div id="header">
    <?php echo \module\page\widgets\Nav::widget()?>
</div>

<style type="text/css">
body.en-us .table-info .info-col>label{
    font-size:14px;
}
</style>

<div class="container" id="base-info-container">
    <div class="lay-g">
        <div class="lay-u-1-2">
            <div class="gallery-view">
                <img src="<?php echo media_url('school-area/images')?>/<?php echo str_replace('/', '&', strtoupper($model->code))?>_LG.jpg">
            </div>
        </div>
        <div class="lay-u-1-2">
            <div class="base-info">
                <h2 style="margin-right:90px;">
                    <?php if (\WS::$app->language === 'en-US'):?>
                        <?php echo $model->getItemData('name')[0]?><span><?php echo $model->getItemData('name')[1]?></span>
                    <?php else:?>
                        <?php echo $model->getItemData('name')[1]?><span><?php echo $model->getItemData('name')[0]?></span>
                    <?php endif?>
                </h2>
                <ul class="main-fields">
                    <li class="field"><label><?php _tt('Rank', '学区排名')?></label><span>NO.<?php echo $model->ranking?></span></li>
                    <li class="field"><label><?php _tt('SAT score', 'SAT平均分')?></label><span><?php echo $model->sat->local[0]?></span></li>
                </ul>
                <div class="grid-info">
                    <h5><?php _tt('Gerenal info', '基本信息')?></h5>
                    <table class="table-info">
                        <tr>
                            <td class="info-col">
                                <span><?php echo number_format($model->special->population) ?? tt('Unknown', '未知')?></span>
                                <label><?php _tt('Population', '人口')?></label>
                            </td>
                            <td class="info-col">
                                <span><?php echo $model->special->jobess_rate ?? tt('Unknown', '未知')?>%</span>
                                <label><?php _tt('Unemployment rate', '失业率')?></label>
                            </td>
                            <td class="info-col"><span>
                                <?php if (\WS::$app->language === 'en-US'):?>
                                    <?php echo number_format($model->special->special2) ?? 'Unknown'?></span>
                                <?php else:?>
                                    <?php echo number_format($model->special->special2 / 10000, 1) ?? 'Unknown'?>万元</span>
                                <?php endif?>
                                <label><?php _tt('Avg income', '人均收入(年)')?></label>
                            </td>
                            <td class="info-col">
                                <span><?php echo $model->special->college_rate ?? tt('Unknown', '未知')?>%</span>
                                <label><?php _tt('Bachelor degree above pct', '大学以上教育比例')?></label>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="racists text-left">
                    <h5><?php _tt('Racial distribution', '种族分布')?></h5>
                    <ul>
                        <?php foreach ($this->context->racials($model->racials) as $item):?>
                            <li style="width:<?php echo $item->width_value?>">
                                <div title="<?php echo $item->name.' '.$item->value?>" class="tooltip-lk bar bar-" style="background:<?php echo $item->bgColor?>;height:<?php echo $item->height?>;"></div>
                                <!--<label><?php echo $item->name?></label>-->
                            </li>
                        <?php endforeach?>
                        </li>
                    </ul>
                </div>
                <div class="houses-go">
                    <?php if ($model->getSummary('total') > 0):?>
                        <a class="go-houses-btn" target="_blank" href="/house/purchase/school-districtss/sd-<?php echo str_replace('/', '%7C', strtolower($model->code))?>/">
                            <?php echo sprintf(tt('%d on Market', '共%d套在售'), $model->getSummary('total'))?>
                            <span class="iconfont icon-goto"></span>
                        </a>
                    <?php else:?>
                        <span class="invalid"><?php _tt('No property available', '暂无可售房源')?></span>
                    <?php endif?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="description">
        <h2><?php _tt('Introduction', '学区介绍')?></h2>
        <p class="desc"><?php echo $model->description?></p>
        <p class="ys"><b><?php _tt('Advantage:', '优势：')?></b> <?php echo $model->advantage?></p>
    </div>
    
    <?php echo \module\schooldistrict\widgets\HouseList::widget([
        'schoolDistrict' => $model
    ])?>

    <?php if ($model->getSummary('total') > 0):?>
        <div class="house-price-dc v-info-blk">
            <h2><?php _tt('Market here', '学区房价')?></h2>
            <table class="top-info table-info">
                <tr>
                    <td class="info-col"><span>
                        <?php if (\WS::$app->language === 'en-US'):?>
                            $<?php echo number_format($model->getSummary('average-price'), 0)?></span>
                        <?php else:?>
                            <?php echo number_format(floatval(str_replace(',', '', $model->getSummary('average-price'))) / 10000, 1)?>万美元</span>
                        <?php endif?>
                        <label><?php _tt('Avg price', '平均房价')?></label>
                    </td>
                    <td class="info-col"><span>
                        $<?php echo number_format($model->getSummary('avergage-rental-price'), 0)?></span>
                        <label><?php _tt('Avg rental', '平均月租')?></label>
                    </td>
                    <td class="info-col">
                        <span><?php echo $model->getSummary('year-down-total')?>套</span>
                        <label><?php _tt('Annual turnover', '年成交量')?></label>
                    </td>
                </tr>
            </table>
            <!--
            <div class="lay-g">
                <div class="lay-u-1-2">
                    #近三年学区房每季度成交量
                </div>
                <div class="lay-u-1-2">
                    #近五年学区房每季度房价走势
                </div>
            </div>
            -->
        </div>
    <?php endif?>
    <div class="sat-scores v-info-blk">
        <h2><?php _tt('SAT score', 'SAT分数')?></h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span>
                        <?php echo $model->sat->local[0]?>
                        <i>( <?php _tt('Reading', '阅读')?> <span><?php echo $model->sat->local[1][0]?></span> | 
                        <?php _tt('Writing', '写作')?> <span><?php echo $model->sat->local[1][1]?></span> | 
                        <?php _tt('Math', '数学')?> <span><?php echo $model->sat->local[1][2]?></span> )</i>
                    </span>
                    <label><?php _tt('Avg SAT score of AREA', '本区SAT平均分')?></label>
                </td>
                <td class="info-col">
                    <span><?php echo $model->sat->state?></span>
                    <label><?php _tt('Avg SAT score of MA', '全州SAT平均分')?></label>
                </td>
                <td class="info-col">
                    <span><?php echo $model->sat->country?></span>
                    <label><?php _tt('Avg SAT score of USA', '全美SAT平均分')?></label>
                </td>
            </tr>
        </table>
    </div>

    <div class="school-info v-info-blk">
        <h2><?php _tt('Schools', '学校信息')?></h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span><?php echo $model->special->special1 ?? _tt('Unknown', '未知')?></span>
                    <label><?php _tt('Student number', '入学人数')?></label>
                </td>
                <td class="info-col">
                    <span>$<?php echo number_format($model->special->special3 ?? '0')?></span>
                    <label><?php _tt('Government subsidies', '人均政府补贴')?></label>
                </td>
                <td class="info-col">
                    <span><?php echo $model->special->special4 ?? '0'?>%</span>
                    <label><?php _tt('Asian student pct', '亚裔学生占比')?></label>
                </td>
            </tr>
        </table>
        <table class="school-list">
            <thead>
                <tr>
                    <th style="text-align:left"><?php _tt('School', '学校')?></th>
                    <th style="text-align:left"><?php _tt('Type', '类型')?></th>
                    <th style="text-align:left"><?php _tt('Website', '官网')?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($model->schools->grade as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('Elementary school', '小学')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->middle as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('Middle school', '初中')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->high as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('High school', '高中')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>

    <?php if (count($model->comments ?? []) > 0):?>
        <div class="hot-comments v-info-blk">
            <h2 class="b-line"><?php _tt('Hot posts', '热门评价')?></h2>
            <?php foreach ($model->comments ?? [] as $comment):?>
                <?php
                    if (! property_exists($comment, 'work_years') && property_exists($comment, 'wordk_years'))
                        $comment->work_years = $comment->wordk_years; // 兼容错误
                ?>
                <div class="comment-row">
                    <div class="lay-g">
                        <div class="lay-u-5-24">
                            <div class="lay-g">
                                <div class="lay-u-1-2">
                                    <img class="image" src="/media/comment/placeholder.jpg">
                                </div>
                                <div class="lay-u-1-2">
                                    <ul class="info-field-list">
                                        <li><?php echo $comment->name?></li>
                                        <li><?php echo $comment->type?></li>
                                        <li><?php echo $comment->work_years?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="lay-u-19-24">
                            <p class="comment-content">
                                <?php echo $comment->content?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->environments) > 0):?>
        <div class="area-envs v-info-blk">
            <h2 class="b-line"><?php _tt('Environments', '区域环境')?></h2>
            <?php foreach ($model->environments as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->features) > 0):?>
        <div class="area-features v-info-blk">
            <h2 class="b-line"><?php _tt('Features', '区域特色')?></h2>
            <?php foreach ($model->features as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>
</div>