<?php
    $this->params['activeNavId'] = 'schooldistrict';
?>


<div id="header">
    <?php echo \module\page\widgets\Nav::widget()?>
</div>

<div class="container" id="base-info-container">
    <div class="lay-g">
        <div class="lay-u-1-2">
            <div class="gallery-view">
                <img src="<?php echo media_url('school-area/images')?>/<?php echo str_replace('/', '&', strtoupper($model->code))?>_LG.jpg">
            </div>
        </div>
        <div class="lay-u-1-2">
            <div class="base-info">
                <h2><?php echo $model->getItemData('name')[1]?><span><?php echo $model->getItemData('name')[0]?></span></h2>
                <ul class="main-fields">
                    <li class="field"><label>学区排名</label><span>NO.<?php echo $model->ranking?></span></li>
                    <li class="field"><label>SAT平均分</label><span><?php echo $model->sat->local[0]?></span></li>
                </ul>
                <div class="grid-info">
                    <h5>基本信息</h5>
                    <table class="table-info">
                        <tr>
                            <td class="info-col"><span><?php echo number_format($model->special->population) ?? '未知'?></span><label>人口</label></td>
                            <td class="info-col"><span><?php echo $model->special->jobess_rate ?? '未知'?>%</span><label>失业率</label></td>
                            <td class="info-col"><span><?php echo number_format($model->special->special3) ?? '未知'?></span><label>人均收入</label></td>
                            <td class="info-col"><span><?php echo $model->special->college_rate ?? '未知'?>%</span><label>大学以上教育比例</label></td>
                        </tr>
                    </table>
                </div>
                <div class="racists text-left">
                    <h5>种族分布</h5>
                    <ul>
                        <?php foreach ($this->context->racials($model->racials) as $item):?>
                            <li style="width:<?php echo $item->value?>">
                                <div title="<?php echo $item->name.' '.$item->value?>" class="tooltip-lk bar bar-" style="background:<?php echo $item->bgColor?>;height:<?php echo $item->height?>;"></div>
                                <!--<label><?php echo $item->name?></label>-->
                            </li>
                        <?php endforeach?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="description">
        <h2>学区介绍</h2>
        <p class="desc"><?php echo $model->description?></p>
        <p class="ys">优势：<?php echo $model->advantage?></p>
    </div>
    <div class="hot-houses v-info-blk">
        <h2>热门房源</h2>
    </div>
    <div class="house-price-dc v-info-blk">
        <h2>学区房价</h2>
        <table class="top-info table-info">
            <tr>
                <td class="info-col"><span>$<?php echo number_format($model->getSummary('avg_price'))?></span><label>平均房价</label></td>
                <td class="info-col"><span>$<?php echo number_format($model->getSummary('avg_monthly_rent_price'))?></span><label>平均月租</label></td>
                <td class="info-col"><span><?php echo $model->getSummary('trading_volume_year')?>套</span><label>年成交量</label></td>
            </tr>
        </table>
        <!--
        <div class="lay-g">
            <div class="lay-u-1-2">
                #近三年学区房每季度成交量
            </div>
            <div class="lay-u-1-2">
                #近五年学区房每季度房价走势
            </div>
        </div>
        -->
    </div>
    <div class="sat-scores v-info-blk">
        <h2>SAT分数</h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span>
                        <?php echo $model->sat->local[0]?>
                        <i>( 阅读 <span><?php echo $model->sat->local[1][0]?></span> | 
                        写作 <span><?php echo $model->sat->local[1][1]?></span> | 
                        数学 <span><?php echo $model->sat->local[1][2]?></span> )</i>
                    </span>
                    <label>本区SAT平均分</label>
                </td>
                <td class="info-col"><span><?php echo $model->sat->state?></span><label>全州SAT平均分</label></td>
                <td class="info-col"><span><?php echo $model->sat->country?></span><label>全美SAT平均分</label></td>
            </tr>
        </table>
    </div>

    <div class="school-info v-info-blk">
        <h2>学校信息</h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span><?php echo $model->special->special1 ?? '未知'?></span>
                    <label>入学人数</label>
                </td>
                <td class="info-col"><span>$<?php echo number_format($model->special->special3 ?? '0')?></span><label>人均政府补贴</label></td>
                <td class="info-col"><span><?php echo $model->special->special4 ?? '0'?>%</span><label>亚裔学生占比</label></td>
            </tr>
        </table>
        <table class="school-list">
            <thead>
                <tr>
                    <th style="text-align:left">学校</th>
                    <th style="text-align:left">类型</th>
                    <th style="text-align:left">官网</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($model->schools->grade as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td>小学</td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->middle as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td>初中</td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->high as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td>高中</td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>

    <?php if (count($model->comments ?? []) > 0):?>
        <div class="hot-comments v-info-blk">
            <h2 class="b-line">热门评价</h2>
            <?php foreach ($model->comments ?? [] as $comment):?>
                <?php
                    if (! property_exists($comment, 'work_years') && property_exists($comment, 'wordk_years'))
                        $comment->work_years = $comment->wordk_years; // 兼容错误
                ?>
                <div class="comment-row">
                    <div class="lay-g">
                        <div class="lay-u-5-24">
                            <div class="lay-g">
                                <div class="lay-u-1-2">
                                    <img class="image" src="/media/comment/placeholder.jpg">
                                </div>
                                <div class="lay-u-1-2">
                                    <ul class="info-field-list">
                                        <li><?php echo $comment->name?></li>
                                        <li><?php echo $comment->type?></li>
                                        <li><?php echo $comment->work_years?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="lay-u-19-24">
                            <p class="comment-content">
                                <?php echo $comment->content?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->environments) > 0):?>
        <div class="area-envs v-info-blk">
            <h2 class="b-line">区域环境</h2>
            <?php foreach ($model->environments as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->features) > 0):?>
        <div class="area-features v-info-blk">
            <h2 class="b-line">区域特色</h2>
            <?php foreach ($model->features as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>
</div>