<?php
    $this->params['activeNavId'] = 'schooldistrict';
?>


<div id="header">
    <?php echo \module\page\widgets\Nav::widget()?>
</div>

<div class="container" id="base-info-container">
    <div class="lay-g">
        <div class="lay-u-1-2">
            <div class="gallery-view">
                <img src="<?php echo media_url('school-area/images')?>/<?php echo str_replace('/', '&', strtoupper($model->code))?>_LG.jpg">
            </div>
        </div>
        <div class="lay-u-1-2">
            <div class="base-info">
                <h2>
                    <?php if (\WS::$app->language === 'en-US'):?>
                        <?php echo $model->getItemData('name')[0]?><span><?php echo $model->getItemData('name')[1]?></span>
                    <?php else:?>
                        <?php echo $model->getItemData('name')[1]?><span><?php echo $model->getItemData('name')[0]?></span>
                    <?php endif?>
                </h2>
                <ul class="main-fields">
                    <li class="field"><label><?php _tt('Rank', '学区排名')?></label><span>NO.<?php echo $model->ranking?></span></li>
                    <li class="field"><label><?php _tt('SAT score', 'SAT平均分')?></label><span><?php echo $model->sat->local[0]?></span></li>
                </ul>
                <div class="grid-info">
                    <h5><?php _tt('Gerenal information', '基本信息')?></h5>
                    <table class="table-info">
                        <tr>
                            <td class="info-col"><span><?php echo number_format($model->special->population) ?? '未知'?></span><label>人口</label></td>
                            <td class="info-col"><span><?php echo $model->special->jobess_rate ?? '未知'?>%</span><label>失业率</label></td>
                            <td class="info-col"><span>
                                <?php if (\WS::$app->language === 'en-US'):?>
                                    <?php echo number_format($model->special->special3) ?? 'Unknown'?></span>
                                <?php else:?>
                                    <?php echo number_format($model->special->special3 / 10000, 1) ?? 'Unknown'?>万元</span>
                                <?php endif?>
                                <label><?php _tt('Avg income', '人均收入(年)')?></label>
                            </td>
                            <td class="info-col"><span><?php echo $model->special->college_rate ?? '未知'?>%</span><label>大学以上教育比例</label></td>
                        </tr>
                    </table>
                </div>
                <div class="racists text-left">
                    <h5><?php _tt('Race distributions', '种族分布')?></h5>
                    <ul>
                        <?php foreach ($this->context->racials($model->racials) as $item):?>
                            <li style="width:<?php echo $item->value?>">
                                <div title="<?php echo $item->name.' '.$item->value?>" class="tooltip-lk bar bar-" style="background:<?php echo $item->bgColor?>;height:<?php echo $item->height?>;"></div>
                                <!--<label><?php echo $item->name?></label>-->
                            </li>
                        <?php endforeach?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="description">
        <h2><?php _tt('School introduction', '学区介绍')?></h2>
        <p class="desc"><?php echo $model->description?></p>
        <p class="ys"><b><?php _tt('Advantage:', '优势：')?></b> <?php echo $model->advantage?></p>
    </div>
    <div class="hot-houses v-info-blk">
        <h2><?php _tt('Hot listings', '热门房源')?></h2>
        <?php echo \module\schooldistrict\widgets\HouseList::widget([
            'schoolDistrict' => $model
        ])?>
    </div>
    <div class="house-price-dc v-info-blk">
        <h2>学区房价</h2>
        <table class="top-info table-info">
            <tr>
                <td class="info-col"><span>
                    <?php if (\WS::$app->language === 'en-US'):?>
                        $<?php echo $model->getSummary('average-price')?></span>
                    <?php else:?>
                        <?php echo number_format(floatval(str_replace(',', '', $model->getSummary('average-price'))) / 10000, 1)?>万美元</span>
                    <?php endif?>
                    <label><?php _tt('Avg price', '平均房价')?></label>
                </td>
                <td class="info-col"><span>$<?php echo $model->getSummary('avergage-rental-price')?></span><label>平均月租</label></td>
                <td class="info-col"><span><?php echo $model->getSummary('year-down-total')?>套</span><label>年成交量</label></td>
            </tr>
        </table>
        <!--
        <div class="lay-g">
            <div class="lay-u-1-2">
                #近三年学区房每季度成交量
            </div>
            <div class="lay-u-1-2">
                #近五年学区房每季度房价走势
            </div>
        </div>
        -->
    </div>
    <div class="sat-scores v-info-blk">
        <h2><?php _tt('SAT score', 'SAT分数')?></h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span>
                        <?php echo $model->sat->local[0]?>
                        <i>( <?php _tt('Reading', '阅读')?> <span><?php echo $model->sat->local[1][0]?></span> | 
                        <?php _tt('Writing', '写作')?> <span><?php echo $model->sat->local[1][1]?></span> | 
                        <?php _tt('Math', '数学')?> <span><?php echo $model->sat->local[1][2]?></span> )</i>
                    </span>
                    <label>本区SAT平均分</label>
                </td>
                <td class="info-col"><span><?php echo $model->sat->state?></span><label>全州SAT平均分</label></td>
                <td class="info-col"><span><?php echo $model->sat->country?></span><label>全美SAT平均分</label></td>
            </tr>
        </table>
    </div>

    <div class="school-info v-info-blk">
        <h2>学校信息</h2>
        <table class="table-info">
            <tr>
                <td class="info-col col-1">
                    <span><?php echo $model->special->special1 ?? _tt('Unknown', '未知')?></span>
                    <label><?php _tt('Student number', '入学人数')?></label>
                </td>
                <td class="info-col"><span>$<?php echo number_format($model->special->special3 ?? '0')?></span><label>人均政府补贴</label></td>
                <td class="info-col"><span><?php echo $model->special->special4 ?? '0'?>%</span><label>亚裔学生占比</label></td>
            </tr>
        </table>
        <table class="school-list">
            <thead>
                <tr>
                    <th style="text-align:left"><?php _tt('School', '学校')?></th>
                    <th style="text-align:left"><?php _tt('Type', '类型')?></th>
                    <th style="text-align:left"><?php _tt('Website', '官网')?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($model->schools->grade as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('Elementary school', '小学')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->middle as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('Middle school', '初中')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
                <?php foreach ($model->schools->high as $item):?>
                    <tr>
                        <td><?php echo $item->name?></td>
                        <td><?php _tt('High school', '高中')?></td>
                        <td><?php echo $item->website?></td>
                    </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>

    <?php if (count($model->comments ?? []) > 0):?>
        <div class="hot-comments v-info-blk">
            <h2 class="b-line">热门评价</h2>
            <?php foreach ($model->comments ?? [] as $comment):?>
                <?php
                    if (! property_exists($comment, 'work_years') && property_exists($comment, 'wordk_years'))
                        $comment->work_years = $comment->wordk_years; // 兼容错误
                ?>
                <div class="comment-row">
                    <div class="lay-g">
                        <div class="lay-u-5-24">
                            <div class="lay-g">
                                <div class="lay-u-1-2">
                                    <img class="image" src="/media/comment/placeholder.jpg">
                                </div>
                                <div class="lay-u-1-2">
                                    <ul class="info-field-list">
                                        <li><?php echo $comment->name?></li>
                                        <li><?php echo $comment->type?></li>
                                        <li><?php echo $comment->work_years?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="lay-u-19-24">
                            <p class="comment-content">
                                <?php echo $comment->content?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->environments) > 0):?>
        <div class="area-envs v-info-blk">
            <h2 class="b-line">区域环境</h2>
            <?php foreach ($model->environments as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>

    <?php if (count($model->features) > 0):?>
        <div class="area-features v-info-blk">
            <h2 class="b-line">区域特色</h2>
            <?php foreach ($model->features as $item):?>
                <div class="env-item">
                    <div class="lay-g">
                        <div class="lay-u-1-8">
                            <span class="label f16"><?php echo $item->name?></span>
                        </div>
                        <div class="lay-u-7-8">
                            <span class="f14"><?php echo $item->description ?? null?></span>
                        </div>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    <?php endif?>
</div>